version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ssl-websites"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lki8enatz23d"
s3_prefix = "ssl-websites"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ImageURI=\"583684070440.dkr.ecr.eu-central-1.amazonaws.com/ssl-websites:2.0\""
image_repositories = []
